### ISSUE TITLE
fix for OSX

### ISSUE THREAD

**Issue by pankona** [pankona/gomo-simra#13]
`app.init()` and `app.Main()` must run on same thread.

**Comment by pankona** [comment]
```
panic: runtime error: index out of range

goroutine 7 [running]:
github.com/pankona/gomo-simra/vendor/golang.org/x/mobile/exp/sprite/glsprite.(*engine).SetTransform(0xc8200d7940, 0xc820018150, 0xc1f78a3ec1fa1720, 0x424087f7430a103d, 0x4377f82dc1a0c5b9)
	/Users/aka/work/gocode/src/github.com/pankona/gomo-simra/vendor/golang.org/x/mobile/exp/sprite/glsprite/glsprite.go:104 +0x94
github.com/pankona/gomo-simra/peer.(*GLPeer).apply(0xc820014280)
	/Users/aka/work/gocode/src/github.com/pankona/gomo-simra/peer/peer.go:178 +0x254
github.com/pankona/gomo-simra/peer.(*GLPeer).Update(0xc820014280)
	/Users/aka/work/gocode/src/github.com/pankona/gomo-simra/peer/peer.go:126 +0x105
github.com/pankona/gomo-simra/gomo.(*Gomo).Start.func1(0x47647b0, 0x428e900)
	/Users/aka/work/gocode/src/github.com/pankona/gomo-simra/gomo/gomobile.go:77 +0x1d2
github.com/pankona/gomo-simra/vendor/golang.org/x/mobile/app.main.func1(0xc82000a8d0)
	/Users/aka/work/gocode/src/github.com/pankona/gomo-simra/vendor/golang.org/x/mobile/app/darwin_amd64.go:59 +0x45
created by github.com/pankona/gomo-simra/vendor/golang.org/x/mobile/app.main
	/Users/aka/work/gocode/src/github.com/pankona/gomo-simra/vendor/golang.org/x/mobile/app/darwin_amd64.go:62 +0x185

goroutine 1 [syscall, locked to thread]:
github.com/pankona/gomo-simra/vendor/golang.org/x/mobile/app._Cfunc_runApp()
	github.com/pankona/gomo-simra/vendor/golang.org/x/mobile/app/_obj/_cgo_gotypes.go:210 +0x31
github.com/pankona/gomo-simra/vendor/golang.org/x/mobile/app.main(0xc82000a8d0)
	/Users/aka/work/gocode/src/github.com/pankona/gomo-simra/vendor/golang.org/x/mobile/app/darwin_amd64.go:64 +0x18a
github.com/pankona/gomo-simra/vendor/golang.org/x/mobile/app.Main(0xc82000a8d0)
	/Users/aka/work/gocode/src/github.com/pankona/gomo-simra/vendor/golang.org/x/mobile/app/app.go:21 +0x21
github.com/pankona/gomo-simra/gomo.(*Gomo).Start(0xc82000e450)
	/Users/aka/work/gocode/src/github.com/pankona/gomo-simra/gomo/gomobile.go:93 +0x80
github.com/pankona/gomo-simra/simra.(*Simra).Start(0xc82000a570, 0xc820016480, 0xc8200164e0)
	/Users/aka/work/gocode/src/github.com/pankona/gomo-simra/simra/engine.go:39 +0xbe
main.main()
	/Users/aka/work/gocode/src/github.com/pankona/gomo-simra/example/main.go:31 +0xde

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/Users/aka/work/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [runnable]:
github.com/pankona/gomo-simra/vendor/golang.org/x/mobile/app.pump.func1(0xc820032070, 0xc820016180)
	/Users/aka/work/gocode/src/github.com/pankona/gomo-simra/vendor/golang.org/x/mobile/app/app.go:163 +0x527
created by github.com/pankona/gomo-simra/vendor/golang.org/x/mobile/app.pump
	/Users/aka/work/gocode/src/github.com/pankona/gomo-simra/vendor/golang.org/x/mobile/app/app.go:192 +0x96

goroutine 6 [runnable]:
main.eventHandle(0xc820016480, 0xc8200164e0)
	/Users/aka/work/gocode/src/github.com/pankona/gomo-simra/example/main.go:14 +0x16e
created by main.main
	/Users/aka/work/gocode/src/github.com/pankona/gomo-simra/example/main.go:30 +0xbc

goroutine 8 [select, locked to thread]:
github.com/pankona/gomo-simra/vendor/golang.org/x/mobile/app.(*app).loop(0x428e900, 0x551d860)
	/Users/aka/work/gocode/src/github.com/pankona/gomo-simra/vendor/golang.org/x/mobile/app/darwin_amd64.go:85 +0x28a
created by github.com/pankona/gomo-simra/vendor/golang.org/x/mobile/app.startloop
	/Users/aka/work/gocode/src/github.com/pankona/gomo-simra/vendor/golang.org/x/mobile/app/darwin_amd64.go:125 +0x41
```
